# Generated by Django 3.2 on 2021-04-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=20),
        ),
    ]
